### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by cjh9** [hyperapp/transitions#13]
The examples here are broken due to the change of the api in ultradom...

https://codepen.io/zaceno/pen/PEmEbW

**Comment by zaceno** [comment]
You're right @cjh9 , but there's more than just the new `render` function I'm afraid. 

At least I changed the `update` function to:

```js
function update () {
    render(Main(), document.body)
} 

```

which seems right according to the README. But there's more stuff breaking that's hard to debug in a codepen. I'm going to have to look deeper into it when I'm at home (and everyone's gone to bed 😅 )

@jorgebucaran Has anything else changed in ultradom 3.0, besides how apps are mounted & patched with the same render function? More specifically, how lifecycle events are treated, or how the virtual-dom is shaped?

**Comment by jorgebucaran** [comment]
@zaceno Yes, sorry, I'm still in the middle of making changes to Ultradom. Some of those changes might make it into Hyperapp at some point, but I can't say for sure.

@cjh9 As a rule of thumb, packages inside the github.com/hyperapp org are fundamentally meant to work with Hyperapp, if it works with anything else is pure coincidence! 😉🙇

**Comment by zaceno** [comment]
@cjh9 Thanks for reporting! I've decided I'm not going to maintain Ultradom (now Superfine) compatibility any more. It may still work, or almost work, but it will be up to you to figure it out. If you want to discuss what changes might be necessary to make it work, come by the Hyperapp slack, and post in the #superfine channel
