### ISSUE TITLE
Broken CDN link

### ISSUE THREAD

**Issue by cjh9** [hyperapp/transitions#16]
The route https://unpkg.com/@hyperapp/transitions doesn't work, 
But this work:
https://unpkg.com/@hyperapp/transitions@1.0.2/dist/transitions.js

So the codepen examples are broken..

**Comment by zaceno** [comment]
@cjh9 Thanks for reporting, and sorry for the embarrasingly long delay!

The link and CodePen examples seem to be working now -- at least for me --, so I'll close. If it stil doesn't work for you, reopen and we'll dig deeper.
