### ISSUE TITLE
'undefined' element created when using transitions

### ISSUE THREAD

**Issue by rexrhino** [hyperapp/transitions#17]
When I use hyperapp/transitions with the following code:

```
import { Enter, Exit } from "transitions"
import { h } from 'hyperapp';

export const Home = () => (state, actions) => (
<Enter easing="ease-in-out" css={{opacity: "0"}}>
  <Exit easing="ease-in-out" css={{opacity: "0", transform: "scale(2.0,2.0)"}}>
    <div key="home"><h1>Home</h1></div>
  </Exit>
</Enter>);
```

It is not showing any transitions, and it is rendering as the following:

```
<undefined easing="ease-in-out" css="[object Object]">
  <undefined easing="ease-in-out" css="[object Object]">
    <div>
      <h1>Home</h1>
    </div>
  </undefined>
</undefined>
```

I am using:
hyperapp/transitions: 1.0.2
hyperapp: 1.2.5

Is this a bug, or a mistake on my part?

**Comment by rexrhino** [comment]
Yes, I am using @hyperapp/router. Here is the rest of the code, index.js first:
```
import { Link, Route, location } from '@hyperapp/router';
import { app, h } from 'hyperapp';

import { About } from './components/about/about.js';
import { Home } from './components/home/home.js';

const state = {
  location: location.state,
};

const actions = {
  location: location.actions,
};

const view = (state, actions) => (
  <div class="app">
    <ul>
      <li>
        <Link to="/">Home</Link>
      </li>
      <li>
        <Link to="/about">About</Link>
      </li>
    </ul>
    <hr />
    <Route path="/" render={Home} />
    <Route path="/about" render={About} />
  </div>
);

const main = app(state, actions, view, document.body);
const unsubscribe = location.subscribe(main.location);
```

And About:
```
import { Enter, Exit } from "transitions"
import { h } from 'hyperapp';

export const About = () => (state, actions) => (
<Enter easing="ease-in-out" css={{opacity: "0"}}>
    <Exit easing="ease-in-out" css={{opacity: "0", transform: "scale(2.0,2.0)"}}>
        <div key="about"><h1>About</h1></div>
    </Exit>
</Enter>);
```

**Comment by zaceno** [comment]
Ah  cool, thought that was what it was. Like I said, it's not the first time someone has issues with the combo transitions + router,  see here: https://github.com/hyperapp/transitions/issues/10

The quirks/bugs are things I can't compensate for or work around in this library, so for the time being, the workaround that works is defining a `Page` component like this:

```
const Page = (_, children) =>
  <div key="page-container">
    <Enter time={500} css={{opacity: "0", transform: "translateY(-100px)"}}>
      <Exit time={500} css={{opacity: "0", transform: "translateY(100px)"}}>
        {children}
      </Exit>
      </Enter>
  </div>

const Home = () => <Page><h2 key="home">Home</h2></Page>
const About = () => <Page><h2 key="about">About</h2></Page>
```

The important point is thing is: each page should be wrapped in a regular vdom node (a `div` in this case) which should all have the *same key* (in this case: "page-container"). And then each page should itself be contained in a single node, with a key that is *different for each page*. 

Try that and see if it helps.

**Comment by rexrhino** [comment]
Thanks! Will try this soon.

**Comment by zaceno** [comment]
@rexrhino How'd it go? I'm going to close here. Feel free to reopen if you're still having problems.

**Comment by rexrhino** [comment]
Sorry it took so long to actually test this! The solution you provided works well. Thanks for your help!
