### ISSUE TITLE
Partial Paints?

### ISSUE THREAD

**Issue by ryanford-frontend** [hyperapp/transitions#18]
I've created a little learning project with hyperapp and @hyperapp/transitions and have run into a strange issue. When adding some of the larger quotes, the containing `blockquote` element appears to only partially paint. If I do anything to alter the screen (i.e. show the browsers toolbar, hover elements in the devtools inspector, tab away and back, highlight the text with `ctrl` + `a` or whatever) it will snap to the correct render.

[The Project Code](https://github.com/ryanford-frontend/quote-generator)

[Live Demo](https://ryanford-frontend.github.io/quote-generator/)

![Partial Paint](https://user-images.githubusercontent.com/20901017/41951389-53fca594-79fd-11e8-97ef-05d4b0a7e319.png)

Just click the quote on the demo and sometimes the larger quotes will reproduce the issue.

I'm using Firefox Quantum 60.0.2 on Ubuntu MATE. Let me know if you need more info.

**Comment by zaceno** [comment]
I tried it and could not replicate (Firefox 61.0 on Mac OS 10.13.4) 😞 

But I don't think any of the quotes that I could get up were as long as the one in your pic. Does it matter how long the quotes are (how large the box needs to be)? Could this be a css/layout issue?

**Comment by ryanford-frontend** [comment]
Removing `transform-style: preserve-3d` fixes it. Closing as it was an issue with my CSS, not your package. Sorry for the confusion.

**Comment by zaceno** [comment]
🍻 No prob! Glad you worked it out!
