### ISSUE TITLE
Can we get an example using @hyperapp/html

### ISSUE THREAD

**Issue by ryanford-frontend** [hyperapp/transitions#9]
Seems the 3 examples all use jsx. Do we need to do something special to make it work with @hyperapp/html?

**Comment by jorgebucaran** [comment]
@ryanford-frontend Nothing "special". [Here you go](https://codepen.io/anon/pen/jzLoqy?editors=0110).

The relevant part is:

```js
  main({}, [
    section({ key: "board" }, [
      Move(
        { easing: "ease-out", time: 200 },
        pieces.map(v =>
                   square(
          { key: v, class: v ? "piece" : "blank", onclick: () => move(v) },
          [v]
        )
                  )
      )
    ]),
    button({ onclick: shuffle }, ["Shuffle"])
  ])
```

Notice I had to make a dummy square function that returns h("square", attrs, children) just to match @zaceno's CSS.

**Comment by zaceno** [comment]
@ryanford-frontend Nothing special needed to make @hyperapp/html work, as @jorgebucaran showd. I can see how my consistent use of JSX might give a different impression though. 

Personally, I use @hyperapp/html sometimes and JSX sometimes. But for examples I prefer JSX (I think it's more readable). And I prefer to be consistent.

So I'm going to close this with no action, but feel free to reopen if you disagree or I'm forgetting something!
